fix: broken links
informatici/openhospital-api pull request #113
Opened 2021-03-22 22:15 UTC by torrespro

2021-03-22 23:49 UTC, mwithi requested changes
Only one line needs fix

2021-03-22 23:49 UTC, mwithi commented on README.md
> +[core]: https://github.com/informatici/openhospital-core
The problem was only here, in the reusable link (https://github.com/informatici/openhospital-core); with this fixed, you can leave unchannged the other ones.

Thanks!

2021-04-02 19:44 UTC, closed without merging

2021-04-02 19:46 UTC, torrespro commented
https://github.com/informatici/openhospital-api/pull/117

2021-04-02 19:46 UTC, torrespro commented
https://github.com/informatici/openhospital-api/pull/117