OP-655 Use interface instead of concreate class
informatici/openhospital-api pull request #141
Opened 2021-09-14 13:00 UTC by dbmalkovsky

See OP-655

2021-09-16 21:12 UTC, mwithi requested changes
Small changes required

2021-09-16 21:12 UTC, mwithi commented on src/main/java/org/isf/accounting/rest/BillController.java
> +		List<PriceList> list = priceListManager.getLists();
indentation?

2021-09-16 21:12 UTC, mwithi commented on src/main/java/org/isf/accounting/rest/BillController.java
> +		List<PriceList> list = priceListManager.getLists();
indentation?

2021-09-16 21:12 UTC, mwithi commented on src/main/java/org/isf/accounting/rest/BillController.java
> +		List<Bill> bills;
indentation?

2021-09-16 21:12 UTC, mwithi commented on src/main/java/org/isf/vaccine/rest/VaccineController.java
>  	    LOGGER.info("Get vaccine by code: {}", vaccineTypeCode);
indentation here

2021-09-16 21:12 UTC, mwithi commented on src/main/java/org/isf/visits/rest/VisitsController.java
>  	    LOGGER.info("Get visit related to patId: {}", patID);
indentation here

2021-09-17 07:03 UTC, dbmalkovsky commented on src/main/java/org/isf/visits/rest/VisitsController.java
>  	    LOGGER.info("Get visit related to patId: {}", patID);
Fixed

2021-09-17 07:03 UTC, dbmalkovsky commented on src/main/java/org/isf/vaccine/rest/VaccineController.java
>  	    LOGGER.info("Get vaccine by code: {}", vaccineTypeCode);
Fixed

2021-09-17 07:03 UTC, dbmalkovsky commented on src/main/java/org/isf/accounting/rest/BillController.java
> +		List<Bill> bills;
Fixed

2021-09-17 07:03 UTC, dbmalkovsky commented on src/main/java/org/isf/accounting/rest/BillController.java
> +		List<PriceList> list = priceListManager.getLists();
Fixed

2021-09-17 07:03 UTC, dbmalkovsky commented on src/main/java/org/isf/accounting/rest/BillController.java
> +		List<PriceList> list = priceListManager.getLists();
Fixed

2021-09-17 07:20 UTC, mwithi approved these changes

2021-09-17 07:20 UTC, merged