OH2-252 | Fix audit logging from API
informatici/openhospital-api pull request #418
Opened 2023-12-20 15:59 UTC by ArnaudFonzam

2023-12-20 21:31 UTC, mwithi commented on src/main/java/org/isf/login/rest/LoginController.java
> -		MDC.put("OHUser", loginRequest.getUsername());
import in line 42 is no longer needed

2023-12-20 21:50 UTC, mwithi commented on src/main/java/org/isf/login/rest/LoginController.java
> +			UserSession.setUser(user);
These should precede `newSessionAudit`

2023-12-20 21:56 UTC, mwithi requested changes
A number of changes requested on both CORE and API, and GUI too.
Apparently logout is not working from API.

2023-12-21 07:44 UTC, ArnaudFonzam commented on src/main/java/org/isf/login/rest/LoginController.java
> +			UserSession.setUser(user);
yes

2023-12-21 08:27 UTC, mwithi commented on src/main/java/org/isf/login/rest/LoginController.java
> +		}
Why to have a separated try/catch block when we can use the same below?

2023-12-21 14:19 UTC, mwithi commented on src/main/java/org/isf/security/CustomLogoutHandler.java
> +			System.out.println("sessionAudit :"+sessionAuditId);
change it to LOGGER or remove println

2023-12-29 17:15 UTC, mwithi approved these changes

2023-12-29 18:18 UTC, dbmalkovsky commented on src/main/java/org/isf/security/ApiAuditorAwareImpl.java
> +package org.isf.security;
Missing license header

2023-12-29 18:19 UTC, dbmalkovsky approved these changes
LGTM; after adding the missing license header

2023-12-30 09:36 UTC, mwithi commented on src/main/java/org/isf/security/ApiAuditorAwareImpl.java
> +package org.isf.security;
Done, thanks!

2023-12-30 10:24 UTC, mwithi commented
Checks fail for a "not-really" breaking change in the oh.yaml specification, will investigate later

2023-12-30 10:25 UTC, merged