OH2-400 | Refactoring ResponseEntity
informatici/openhospital-api pull request #482
Opened 2024-10-14 07:43 UTC by SilverD3

See OH2-400

### Tasks

- [ ] `org/isf/accounting/rest/BillController.java`
- [ ] `org/isf/admission/rest/AdmissionController.java`
- [ ] `org/isf/admtype/rest/AdmissionTypeController.java`
- [ ] `org/isf/agetype/rest/AgeTypeController.java`
- [ ] `org/isf/disctype/rest/DischargeTypeController.java`
- [ ] `org/isf/disease/rest/DiseaseController.java`
- [ ] `org/isf/distype/rest/DiseaseTypeController.java`
- [ ] `org/isf/dlvrrestype/rest/DeliveryResultTypeController.java`
- [ ] `org/isf/dlvrtype/rest/DeliveryTypeController.java`
- [ ] `org/isf/exam/rest/ExamController.java`
- [ ] `org/isf/exam/rest/ExamRowController.java`
- [ ] `org/isf/examination/rest/ExaminationController.java`
- [ ] `org/isf/exatype/rest/ExamTypeController.java`
- [ ] `org/isf/hospital/rest/HospitalController.java`
- [ ] `org/isf/lab/rest/LaboratoryController.java`
- [ ] `org/isf/login/rest/LoginController.java`
- [ ] `org/isf/malnutrition/rest/MalnutritionController.java`
- [ ] `org/isf/medical/rest/MedicalController.java`
- [ ] `org/isf/medicalstock/rest/MedicalStockMovementController.java`
- [ ] `org/isf/medicalstock/rest/StockMovementController.java`
- [ ] `org/isf/medicalstockward/rest/MedicalStockWardController.java`
- [ ] `org/isf/medstockmovtype/rest/MedStockMovementTypeController.java`
- [ ] `org/isf/medtype/rest/MedicalTypeController.java`
- [ ] `org/isf/opd/rest/OpdController.java`
- [ ] `org/isf/operation/rest/OperationController.java`
- [ ] `org/isf/opetype/rest/OperationTypeController.java`
- [ ] `org/isf/patconsensus/rest/PatientConsensusController.java`
- [ ] `org/isf/patient/rest/PatientController.java`
- [ ] `org/isf/patvac/rest/PatVacController.java`
- [ ] `org/isf/permissions/rest/PermissionController.java`
- [ ] `org/isf/pregtreattype/rest/PregnantTreatmentTypeController.java`
- [ ] `org/isf/priceslist/rest/PriceListController.java`
- [ ] `org/isf/pricesothers/rest/PricesOthersController.java`
- [ ] `org/isf/sms/rest/SmsController.java`
- [ ] `org/isf/stats/rest/ReportsController.java`
- [ ] `org/isf/supplier/rest/SupplierController.java`
- [ ] `org/isf/therapy/rest/TherapyController.java`
- [ ] `org/isf/usergroups/rest/UserGroupController.java`
- [ ] `org/isf/users/rest/UserController.java`
- [ ] `org/isf/usersettings/rest/UserSettingController.java`
- [ ] `org/isf/vaccine/rest/VaccineController.java`
- [ ] `org/isf/vactype/rest/VaccineTypeController.java`
- [ ] `org/isf/visits/rest/VisitsController.java`
- [ ] `org/isf/ward/rest/WardController.java`

2024-10-21 16:14 UTC, SteveGT96 requested changes
It would be better to remoive also response entity on endoint like this one. Instead of returning NoConent when the list us empty or null, we should return an empty list with status 200.

2024-10-21 16:14 UTC, SteveGT96 commented on src/main/java/org/isf/accounting/rest/BillController.java
>  	public ResponseEntity<List<BillDTO>> searchBills(
```suggestion
	@GetMapping("/bills")
	public List<BillDTO> searchBills(
```

2024-10-28 20:06 UTC, mwithi commented
Please resolve conflicts

2024-10-29 10:41 UTC, mwithi commented
@SilverD3 please merge develop and update again the spec file, thanks

2024-10-29 10:57 UTC, SilverD3 commented
@mwithi up-to-date

2024-10-29 15:26 UTC, mwithi commented
> @mwithi up-to-date

Thanks. Are all these breaking changes meant to be?

https://github.com/informatici/openhospital-api/actions/runs/11572320351/job/32212045163?pr=482#step:19:19

2024-10-30 08:39 UTC, SilverD3 commented
Yes. I will align the UI

2024-10-30 09:32 UTC, mwithi commented
> Yes. I will align the UI

Ok, please, start doing it and create a PR on UI with same branch name, thanks!

2024-11-06 09:38 UTC, SilverD3 commented
@mwithi paired PR on the UI already created

2024-11-06 13:55 UTC, mwithi commented
> git pull https://github.com/SilverD3/openhospital-api.git OH2-400_responseentity_refactoring

best way to test is to do random tests on any endpoint with the new UI, right?

2024-11-06 13:55 UTC, mwithi commented
> @mwithi paired PR on the UI already created

@SilverD3 best way to test is to do random tests on any endpoint with the new UI, right?

2024-11-06 16:38 UTC, SilverD3 commented
> @SilverD3 best way to test is to do random tests on any endpoint with the new UI, right?

Yes, just to ensure that nothing is broken with the removal of ResponseEntity

2024-11-08 09:57 UTC, mwithi approved these changes
LGTM. Thanks a lot!

2024-11-08 09:57 UTC, merged